### ISSUE TITLE
BUG:Channel name must start with a letter

### ISSUE THREAD

**Issue by buttering** [zhaxzhax/p2p-chat-specification#13]
![1](https://user-images.githubusercontent.com/54806742/86892822-57473a00-c133-11ea-8475-fe983fa8132c.png)

**Comment by zhaxzhax** [comment]
Have some one solved this one? If not, I'm gonon have a try.

**Comment by zhaxzhax** [comment]
@buttering  
Have this commit solved your problem？
If it did，you could close this issue.

**Comment by buttering** [comment]
Nice!You did a goog job
