### ISSUE TITLE
BUG:Only the top of the newly created ChatItem can be clicked

### ISSUE THREAD

**Issue by buttering** [zhaxzhax/p2p-chat-specification#14]
![image](https://user-images.githubusercontent.com/54806742/86899218-4f3fc800-c13c-11ea-9a9f-e451c015cb2a.png)

**Comment by zhaxzhax** [comment]
Maybe someone have solved this problem.
Maybe you could close this issue.

**Comment by buttering** [comment]
I will close this issue.

**Comment by zhaxzhax** [comment]
It seems like this bug haven‘t been fixed.’
